name: gPhotos2Immich
version: "2026.06.27.2110"
slug: gphotos2immich
description: Sync Google Photos shared albums to Immich
arch:
  - amd64
  - aarch64
init: false
host_network: true
boot: auto
startup: application
