name: gPhotos2Immich
version: "0.0.0"
slug: gphotos2immich
description: Sync Google Photos shared albums to Immich
arch:
  - amd64
  - aarch64
init: false
boot: auto
startup: application
ingress: true
ingress_port: 8099
panel_icon: mdi:image-sync
panel_title: Photo Sync
panel_admin: false
